bid_api/urls.py
from django.conf.urls import url
from django.urls import path

from .views import info, badger

app_name = "bid_api"
urlpatterns = [
    path("me", info.UserSelfInfoView.as_view(), name="me"),
    path("user", info.UserSelfInfoView.as_view(), name="user"),
    path("userinfo", info.OpenIDUserInfoView.as_view(), name="userinfo"),
    url(
        r"^user/(?P<user_id>\d+)$", info.UserInfoView.as_view(), name="user-info-by-id"
    ),
    url(
        r"^user/(?P<user_id>\d+)/avatar$",
        info.UserAvatarView.as_view(),
        name="user-avatar",
    ),
    url(
        r"^badges/(?P<user_id>\d+)$",
        info.UserBadgeView.as_view(),
        name="user-badges-by-id",
    ),
    url(
        r"^badges/(?P<user_id>\d+)/html$",
        info.BadgesHTMLView.as_view(),
        name="user-badges-html",
    ),
    path(
        "badger/grant/<badge>/<uuid>",
        badger.BadgerView.as_view(action="grant"),
        name="badger_grant",
    ),
    path(
        "badger/revoke/<badge>/<uuid>",
        badger.BadgerView.as_view(action="revoke"),
        name="badger_revoke",
    ),
    url(
        r"^badges/(?P<user_id>\d+)/html/(?P<size>[a-z])$",
        info.BadgesHTMLView.as_view(),
        name="user-badges-html",
    ),
    path("stats", info.StatsView.as_view(), name="stats"),
]

# noinspection PyUnresolvedReferences
from . import signals as _

bid_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import forms
from .views import normal_pages, registration_email, json_api, developer_request

app_name = "bid_main"
urlpatterns = [
    url(r"^$", normal_pages.IndexView.as_view(), name="index"),
    url(r"^settings/profile$", normal_pages.ProfileView.as_view(), name="profile"),
    url(r"^login$", normal_pages.LoginView.as_view(), name="login"),
    url(
        r"^logout$",
        normal_pages.LogoutView.as_view(next_page="bid_main:login"),
        name="logout",
    ),
    url(r"^switch/?$", normal_pages.SwitchUserView.as_view(), name="switch_user"),
    url(
        r"^switch/(?P<switch_to>.+)$",
        normal_pages.SwitchUserView.as_view(),
        name="switch_user",
    ),
    url(r"^delete-my-account$", normal_pages.DeleteUserView.as_view(), name="delete_user"),
    url(
        r"^privacy-policy/agree$",
        normal_pages.PrivacyPolicyAgreeView.as_view(),
        name="privacy_policy_agree",
    ),
    url(
        r"^badge-toggle-private",
        json_api.BadgeTogglePrivateView.as_view(),
        name="badge_toggle_private",
    ),
    url(
        "^change$",
        auth_views.PasswordChangeView.as_view(
            form_class=forms.PasswordChangeForm,
            success_url=reverse_lazy("bid_main:password_change_done"),
        ),
        name="password_change",
    ),
    url(
        "^change-password/done$",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    url(
        r"^password_reset/$",
        auth_views.PasswordResetView.as_view(
            form_class=forms.PasswordResetForm,
            success_url=reverse_lazy("bid_main:password_reset_done"),
        ),
        name="password_reset",
    ),
    url(
        r"^password_reset/done/$",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    url(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("bid_main:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    url(
        r"^password_reset/complete/$",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("ev-members", json_api.EvMembersView.as_view(), name="ev-members"),
    path(
        "user/<slug:nickname>/",
        normal_pages.PublicProfileView.as_view(),
        name="public-profile",
    ),
    url(
        r"^confirm-email/start$",
        registration_email.ConfirmEmailView.as_view(),
        name="confirm-email",
    ),
    url(
        r"^confirm-email/start-change$",
        registration_email.ConfirmEmailView.as_view(
            template_name="bid_main/confirm_email/change.html"
        ),
        name="confirm-email-change",
    ),
    url(
        r"^confirm-email/cancel-change$",
        registration_email.CancelEmailChangeView.as_view(),
        name="cancel-email-change",
    ),
    url(
        r"^confirm-email/sent$",
        registration_email.ConfirmEmailSentView.as_view(),
        name="confirm-email-sent",
    ),
    url(
        r"^confirm-email/verified/(?P<info>[^/]+)/(?P<hmac>[^/]+)$",
        registration_email.ConfirmEmailVerifiedView.as_view(),
        name="confirm-email-verified",
    ),
    url(
        r"^confirm-email/poll$",
        registration_email.ConfirmEmailPollView.as_view(),
        name="confirm-email-poll",
    ),
]

if not settings.DISABLE_ACOUNT_CREATION:
    urlpatterns += [
        # Source of registration machinery:
        # http://musings.tinbrain.net/blog/2014/sep/21/registration-django-easy-way/
        url(
            r"^register/$",
            registration_email.RegistrationView.as_view(),
            name="register",
        ),
        url(
            r"^register/signed-up/$",
            auth_views.PasswordResetDoneView.as_view(
                template_name="registration/initial_signed_up.html"
            ),
            name="register-done",
        ),
        url(
            r"^register/password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
            registration_email.InitialSetPasswordView.as_view(),
            name="register-confirm",
        ),
        url(
            r"^register/complete/$",
            auth_views.PasswordResetCompleteView.as_view(
                template_name="registration/registration_complete.html"
            ),
            name="register-complete",
        ),
    ]

if settings.ENABLE_DEV_REQUESTS:
    urlpatterns += [
        path(
            "developer-access-pending",
            developer_request.DeveloperRequestPending.as_view(),
            name="developer-access-pending",
        ),
        path(
            "developer-access-request",
            developer_request.DeveloperRequestView.as_view(),
            name="developer-access-request",
        ),
        path(
            "developer-access-cancel",
            developer_request.DeveloperRequestCancelView.as_view(),
            name="developer-access-cancel",
        ),
        path(
            "developer-access-request/verification/<int:pk>",
            developer_request.DeveloperRequestVerificationView.as_view(),
            name="developer-access-request-verification",
        ),
    ]

# Only enable this on a dev server:
if settings.DEBUG:
    from .views import testviews

    urlpatterns += [
        url(r"^debug/email-changed$", testviews.test_mail_email_changed),
        url(r"^debug/email-verify$", testviews.test_mail_verify_address),
        url(r"^error/(?P<code>\d+)$", testviews.test_error),
    ]

bid_main/views/developer_request.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.views.generic import FormView, UpdateView, TemplateView, View
from django.shortcuts import redirect
from django.contrib import messages

from .. import forms, models


class DeveloperRequestView(LoginRequiredMixin, FormView):
    template_name = "bid_main/developer_request.html"
    form_class = forms.DeveloperAccessRequestForm
    success_url = "/"

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        if models.DeveloperAccessRequest.objects.filter(user=request.user):
            return redirect("/developer-access-pending")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: forms.DeveloperAccessRequestVerificationForm):
        request_model = form.save(commit=False)
        request_model.user = self.request.user
        request_model.save()
        return super().form_valid(form)


class DeveloperRequestPending(LoginRequiredMixin, TemplateView):
    template_name = "bid_main/developer_request_pending.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["developer_request"] = self.developer_request
        return context

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        try:
            self.developer_request = models.DeveloperAccessRequest.objects.get(
                user=request.user
            )
            return super().dispatch(request, *args, **kwargs)
        except models.DeveloperAccessRequest.DoesNotExist:
            return redirect("/developer-access-request")


class DeveloperRequestCancelView(LoginRequiredMixin, View):
    def dispatch(self, request: HttpRequest, *args, **kwargs):
        models.DeveloperAccessRequest.objects.filter(user=request.user).delete()
        return redirect("/")


class DeveloperRequestVerificationView(LoginRequiredMixin, UpdateView):
    template_name = "bid_main/developer_request_verification.html"
    fields = ["sponsor_agreed"]
    model = models.DeveloperAccessRequest
    success_url = "/"

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        request_model = models.DeveloperAccessRequest.objects.filter(
            pk=kwargs.get("pk")
        )
        if not request_model.exists():
            messages.add_message(
                request,
                messages.INFO,
                "Request not found. Probably already accepted or refused.",
            )
            return redirect("/")
        if request.user != request_model[0].sponsor:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: forms.DeveloperAccessRequestVerificationForm):
        request_model = form.save(commit=False)
        request_model.user = self.request.user
        request_model.save()
        return super().form_valid(form)

bid_main/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""

    # TODO(Sybren): respond as JSON when this is an XHR.

    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        if request is None or request.method in {"HEAD", "OPTIONS"}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view,
        response = self.render_to_response(self.get_context_data(**kwargs))
        response.status_code = self.status
        return response


def csrf_failure(request, reason=""):
    import django.views.csrf

    return django.views.csrf.csrf_failure(
        request, reason=reason, template_name="errors/403_csrf.html"
    )

bid_main/views/json_api.py
# SPDX-FileCopyrightText: (C) 2018 Sybren A. Stüvel <sybren@stuvel.eu>
# SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>
#
# SPDX-LicenseRef: GPL-3.0-or-later

"""JSON views that aren't real API calls.

Those are used by regular views, and contrary to real API calls (which would
live in bid_api) expect authentication via the sessions and CSRF checks rather
than via bearer tokens.
"""

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.http.request import HttpRequest
from django.shortcuts import get_object_or_404
from django.views.generic import View

from .. import models

log = logging.getLogger(__name__)


class BadgeTogglePrivateView(LoginRequiredMixin, View):
    """JSON endpoint that toggles 'is_private' flag for badges."""

    def post(self, request: HttpRequest, *args, **kwargs) -> JsonResponse:
        try:
            badge_name = request.POST["badge_name"]
        except KeyError:
            return JsonResponse({"_message": "no badge name given"}, status=422)

        role: models.Role = get_object_or_404(models.Role.objects, name=badge_name)
        if request.user.private_badges.filter(id=role.id).count():
            request.user.private_badges.remove(role)
            now_private = False
        else:
            request.user.private_badges.add(role)
            now_private = True

        return JsonResponse({"is_private": now_private})


class EvMembersView(View):
    """
    JSON endpoint to get all the e.V. members.
    It is used in ev.kde.org/members
    """

    def get(self, request: HttpRequest) -> JsonResponse:
        users = []
        for user in models.User.objects.filter(roles__name__exact="ev-active"):
            users.append(user.full_name)
        return JsonResponse({"members": users})

bid_main/views/mixins.py
"""Mix-in classes for views."""
import logging
import urllib.parse

from django.urls import reverse_lazy

log = logging.getLogger(__name__)


class PageIdMixin:
    page_id = ""

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["page_id"] = self.page_id
        return ctx


class RedirectToPrivacyAgreeMixin:
    privacy_policy_agree_url = reverse_lazy("bid_main:privacy_policy_agree")

    def get_success_url(self):
        """Return the user-originating redirect URL if it's safe."""

        regular_redir_url = super().get_success_url()
        if not self.request.user.must_pp_agree:
            return regular_redir_url

        # User must agree to privacy policy first before being redirected.
        next_url_qs = urllib.parse.urlencode(
            {
                "next": regular_redir_url,
            }
        )
        redirect_to = f"{self.privacy_policy_agree_url}?{next_url_qs}"
        log.debug("Directing user to %s", redirect_to)
        return redirect_to

bid_main/views/oauth2.py
"""Our own hooks into the OAuth2 flow."""

import logging

from django.http import HttpResponse
from django.shortcuts import render
from oauth2_provider import views as base_views
from oauth2_provider.models import get_application_model

from bid_main import forms

log = logging.getLogger(__name__)
OAuth2Application = get_application_model()


class AuthorizationView(base_views.AuthorizationView):
    """Refuses to authorize user with unconfirmed email."""

    log = log.getChild("AuthorizationView")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.has_confirmed_email:
            return self.force_email_confirm(request)

        _, credentials = self.validate_authorization_request(request)
        application = OAuth2Application.objects.get(client_id=credentials["client_id"])
        if application.authorized_roles.exists():
            has_role = False
            for role in application.authorized_roles.all():
                if role in request.user.roles.all():
                    has_role = True

            if not has_role:
                return HttpResponse(
                    "You are not authorized to connect to this applications", status=401
                )
        return super().get(request, *args, **kwargs)

    def force_email_confirm(self, request):
        """Disrupt the OAuth2 flow by forcing the user to confirm their email."""

        # This copies some stuff from the superclass to figure out the OAuth2 application.
        _, credentials = self.validate_authorization_request(request)
        application = OAuth2Application.objects.get(client_id=credentials["client_id"])

        self.log.info(
            "Forcing user to confirm email before allowing OAuth2 flow with app %r.",
            application.name,
        )

        qs = request.META.get("QUERY_STRING", "")
        requested = f"{request.path}?{qs}" if qs else request.path
        self.log.debug("Their original URL was %r", requested)

        ctx = {
            "form": forms.ConfirmEmailStartForm(
                {"next_url": requested, "next_name": application.name}
            ),
            "next_name": application.name,
            "user": request.user,
        }
        return render(request, "bid_main/confirm_email/start_for_oauth.html", ctx)

bid_main/views/testviews.py
"""Views for testing certain functionality."""


def test_mail_email_changed(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_email_changed_mail

    email_body_html, *_ = construct_email_changed_mail(request.user, "old@email.nl")

    return HttpResponse(email_body_html)


def test_mail_verify_address(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_verify_address

    email_body_html, *_ = construct_verify_address(request.user, request.scheme)
    return HttpResponse(email_body_html)


def test_error(request, code):
    from django.core import exceptions
    from django.http import response, Http404

    codes = {
        403: exceptions.PermissionDenied,
        404: Http404,
        500: exceptions.ImproperlyConfigured,
    }
    try:
        exc = codes[int(code)]
    except KeyError:
        return response.HttpResponse(f"error test for code {code}", status=int(code))
    else:
        raise exc(f"exception test for code {code}")

templates/bid_main/about.html
{% extends 'layout.html' %}
{% block page_title %}About My KDE{% endblock %}
{% block body %}
{% block before_about_bid %}{% endblock %}
<div class="bid box about">
  <h3>Technical Assistance</h3>
  <p>
    For any issue or request regarding your KDE Account, such as merging accounts or fixing an
    invalid email address, get in touch with sysadmin at kde.org. We will help you right away!
  </p>
</div>{% block after_about_bid %}{% endblock %}
{% endblock %}

templates/bid_main/index.html
{% extends 'profile_layout.html' %}

{% load static %}
{% load avatar badges %}

{% block page_title %}
  {% if user.full_name %}
    {{ user.full_name }}'s
  {% else %}
    Your
  {% endif %}
  Profile
{% endblock %}

{% block setting %}
  <div class="bg-light py-3 border-bottom">
    <div class="d-flex align-items-center">
      <div class="col-auto my-auto">
        {% avatar %}
      </div>
      <div class="col">
        <h2 class="mt-0">
          {% if user.full_name %}
            {{ user.full_name }}
          {% else %}
            <a href="{% url 'bid_main:profile' %}">Name missing. Complete your profile</a>
          {% endif %}
        </h2>
        <p><strong>Username:</strong> "{{ user.nickname }}"</p>
        {% if user.email_change_preconfirm %}
          <p class="bg-warning p-1">
            A change from {{ user.email }} to {{ user.email_change_preconfirm }} is pending.<br/><a
            href="javascript:$('#cancel_email_change').submit()">Cancel this change</a> or <a
            href="{% url 'bid_main:confirm-email-change' %}">re-send confirmation email</a>.
          </p>
        {% else %}
          <p><strong>Email: </strong>{{ user.email }}</p>
        {% endif %}
        {% if show_confirm_address %}
          <p class="bg-warning p-1">
            <a href="{% url 'bid_main:confirm-email' %}">Confirm your email address</a> to unleash the full power of
            KDE Accounts.
          </p>
        {% endif %}
        {% if user.public_profile %}
          <a href="{% url 'bid_main:public-profile' user.nickname %}">Public profile</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="px-3">
    <section>
      {% if settings.ENABLE_DEV_REQUESTS and developer_access_requests|length > 0 %}
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h2 class="mt-0 h4 alert-heading">Developer requests to accept or deny</h2>

          <div class="list-group">
            {% for dev_request in developer_access_requests %}
              <a href="{% url 'bid_main:developer-access-request-verification' pk=dev_request.pk %}">
                {{ dev_request.user.full_name }}
                <span class="badge badge-primary badge-pill">{{ dev_request.sponsor_choice }}</span>
              </a>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      <form id="cancel_email_change" action="{% url 'bid_main:cancel-email-change' %}"
            method="POST">{% csrf_token %}</form>
    </section>

    <section class="mt-3">
      <h3>Your Badges</h3>
      {% with badges=user.all_badges %}
        {% if badges %}
          <ul class="badges">
            {% for badge in badges %}
              {% render_badge badge %}
            {% endfor %}
          </ul>
          <p>
            You have earned {{ badges|length }} badge{{ badges|pluralize }}. If you do not want to show
            those badges on connected websites, you can mark them as private.
          </p>
        {% else %}
          <p>
            You don't have any badges. You can earn badges in various ways, for example by being a KDE developer.
          </p>
        {% endif %}
      {% endwith %}
    </section>

    {% comment %}
    <section class="mt-3">
      <h3>Your KDE Services</h3>
      {% if apps %}
        <p>
          You have granted the following applications access to your KDE Accounts; in other
          words, you used your KDE Accounts to log in there. Click on the cross to remove
          all authentication tokens for those apps, effectively logging you out there.
        </p>
      {% else %}
        <p>
          You have not granted any KDE services access to your KDE Accounts; in other words,
          you have not used your KDE Accounts to log in anywhere yet. When you do, this is
          the place where you will be able to revoke that access from those applications.
        </p>
      {% endif %}
      <form id="revokeform" method="post" action="">
        {% csrf_token %}
        {{ form.app_id }}
        {{ form.errors }}
      </form>
      <ul>
        {% for app in apps %}
          <li>
            <div class="app-info">
              {{ app }}
              {% if app.url %}<a class="app-url" href="{{ app.url }}" target="_blank">{{ app.url }}</a>{% endif %}
            </div>
            <a class="app-revoke" title="Remove {{ app }} authentication token" href="javascript:revoke({{ app.id }})">Revoke
              Access</a>
          </li>
        {% endfor %}
      </ul>
    </section>
    {% endcomment %}
  </div>
{% endblock %}

{% block footer_scripts %}
  <script src="{% static 'assets_vendor/js/toastr.min.js' %}"></script>
  <script src="{% static 'assets_vendor/js/js.cookie.min.js' %}"></script>
  <script>
  function toggle_badge_privacy(event) {
    let badge_name = event.target.dataset.badgeName;

    $.post("{% url 'bid_main:badge_toggle_private'  %}", {
      csrfmiddlewaretoken: Cookies.get('csrftoken'),
      badge_name: badge_name,
    })
      .fail(function (error) {
        toastr.error(xhrErrorResponseMessage(error), 'Unable to toggle badge privacy');
      })
      .done(function (response) {
        let $badge = $('li.badge.' + badge_name);
        if (response.is_private) {
          $badge.addClass('private');
        } else {
          $badge.removeClass('private');
        }
      });
  }

  $(function () {
    //$("input[data-toggle]").bootstrapToggle();
    $("input[type='checkbox'][data-badge-name]").change(toggle_badge_privacy);
  })
  </script>
{% endblock %}

templates/bid_main/profile.html
{% extends 'profile_layout.html' %}
{% load avatar %}
{% load static %}
{% block page_title %}Edit Your Profile{% endblock %}
{% block head %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="/martor/css/martor.min.css" type="text/css" media="all" rel="stylesheet" />
  <style>
    .avatar-editor {
      align-items: center;
      justify-content: center;
      padding-right: 2mm;
    }

    .avatar-editor img {
      margin-right: 2mm;
      border-right: thin solid var(--border-color);
    }
  </style>
{% endblock %}
{% block setting %}
  <div>
    <h2 class="h3 mx-3 mt-3">Edit Profile</h2>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="card-body">
        <h4 class="mt-1">Information required</h4>
        <!-- Full name input-->
        <label class="control-label">Full Name</label>
        <div class="form-group {% if not user.full_name %}form-required{% endif %}">{{ form.full_name }}</div>
        {{ form.full_name.errors }}

        <!-- Email display-->
        <label class="control-label">Email</label>
        <div class="form-group">{{ form.email }}</div>{% if user.email_change_preconfirm %}
        <p class="help-text">A change to {{ user.email_change_preconfirm }} is already pending.<br/><a
          href="javascript:$('#cancel_email_change').submit()">Cancel this change</a> or <a
          href="{% url 'bid_main:confirm-email-change' %}">re-send confirmation email</a>.
        </p>{% endif %}
        {% comment %}
          <!-- Nickname input-->
          <label class="control-label">Nickname</label>
          <div class="form-group">{{ form.nickname }}</div>{{ form.nickname.errors }}
          {{ form.non_field_errors }}
          {% endcomment %}
        <!-- Avatar input-->
        <label class="control-label">Avatar</label>
        <div class="form-group avatar-editor d-flex">
          {% avatar size=64 %}
          <input class="form-control-file mt-2" id="avatar-file-input" type="file" name="avatar"/>
        </div>
        <div class="form-check">
          <input type="checkbox" name="avatar-clear" id="avatar-clear" />
          <label for="avatar-clear" class="mt-2">Clear</label>
        </div>
        {{ form.avatar.errors }}

        <hr />

        <h4 class="mt-1">Information for profile pages</h4>

        <p>Your profile page is available <a href="{% url "bid_main:public-profile" user.nickname %}">here</a></p>

        <div class="form-check">
          {{ form.public_profile }}
          <label class="form-check-label" for="{{ form.public_profile.id_for_label }}">
            {{ form.public_profile.label }}
          </label>
          <br />
          <small>A public profile can be seen by everyone</small>
        </div>

        {{ form.bio }}

        <div class="form-group">
          <label class="control-label" for="{{ form.homepage.id_for_label }}">{{ form.homepage.label }}</label>
          {{ form.homepage }}
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.matrix_nick.id_for_label }}">{{ form.matrix_nick.label }}</label>
          {{ form.matrix_nick }}
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.irc_nick.id_for_label }}">{{ form.irc_nick.label }}</label>
          {{ form.irc_nick }}
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.mastodon_nick.id_for_label }}">{{ form.mastodon_nick.label }}</label>
          {{ form.mastodon_nick }}
	  <div class="valid-feedback">
	  </div>
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.twitter_nick.id_for_label }}">{{ form.twitter_nick.label }}</label>
          {{ form.twitter_nick }}
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.liberapay_nick.id_for_label }}">{{ form.liberapay_nick.label }}</label>
          {{ form.liberapay_nick }}
        </div>
      </fieldset>
      <div class="border-top p-3">
        <button class="btn btn-filled-success btn-success" type="submit">Save Changes</button>
        <a class="btn btn-danger ml-2" href="{% url 'bid_main:index' %}">Discard Changes</a>
        <a class="btn btn-link" href="{% url 'bid_main:password_change' %}">Change Password</a>
      </div>
    </form>
    <form id="cancel_email_change" action="{% url 'bid_main:cancel-email-change' %}"
          method="POST">{% csrf_token %}</form>
  </div>
  {% if user.is_staff %}
    <div class="bid-links m-3"><a href="{% url 'admin:bid_main_user_change' user.id %}">Edit account in admin</a>
    </div>
  {% endif %}
  {% block js %}

  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="/martor/js/martor.min.js"></script>
  {% endblock %}
{% endblock %}