bid_api/urls.py
from django.conf.urls import url
from django.urls import path

from .views import info, badger

app_name = "bid_api"
urlpatterns = [
    path("me", info.UserSelfInfoView.as_view(), name="me"),
    path("user", info.UserSelfInfoView.as_view(), name="user"),
    path("userinfo", info.OpenIDUserInfoView.as_view(), name="userinfo"),
    url(
        r"^user/(?P<user_id>\d+)$", info.UserInfoView.as_view(), name="user-info-by-id"
    ),
    url(
        r"^user/(?P<user_id>\d+)/avatar$",
        info.UserAvatarView.as_view(),
        name="user-avatar",
    ),
    url(
        r"^badges/(?P<user_id>\d+)$",
        info.UserBadgeView.as_view(),
        name="user-badges-by-id",
    ),
    url(
        r"^badges/(?P<user_id>\d+)/html$",
        info.BadgesHTMLView.as_view(),
        name="user-badges-html",
    ),
    path(
        "badger/grant/<badge>/<uuid>",
        badger.BadgerView.as_view(action="grant"),
        name="badger_grant",
    ),
    path(
        "badger/revoke/<badge>/<uuid>",
        badger.BadgerView.as_view(action="revoke"),
        name="badger_revoke",
    ),
    url(
        r"^badges/(?P<user_id>\d+)/html/(?P<size>[a-z])$",
        info.BadgesHTMLView.as_view(),
        name="user-badges-html",
    ),
    path("stats", info.StatsView.as_view(), name="stats"),
]

# noinspection PyUnresolvedReferences
from . import signals as _

bid_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import forms
from .views import normal_pages, registration_email, json_api, developer_request

app_name = "bid_main"
urlpatterns = [
    url(r"^$", normal_pages.IndexView.as_view(), name="index"),
    url(r"^settings/profile$", normal_pages.ProfileView.as_view(), name="profile"),
    url(r"^login$", normal_pages.LoginView.as_view(), name="login"),
    url(
        r"^logout$",
        normal_pages.LogoutView.as_view(next_page="bid_main:login"),
        name="logout",
    ),
    url(r"^switch/?$", normal_pages.SwitchUserView.as_view(), name="switch_user"),
    url(
        r"^switch/(?P<switch_to>.+)$",
        normal_pages.SwitchUserView.as_view(),
        name="switch_user",
    ),
    url(r"^delete-my-account$", normal_pages.DeleteUserView.as_view(), name="delete_user"),
    url(
        r"^privacy-policy/agree$",
        normal_pages.PrivacyPolicyAgreeView.as_view(),
        name="privacy_policy_agree",
    ),
    url(
        r"^badge-toggle-private",
        json_api.BadgeTogglePrivateView.as_view(),
        name="badge_toggle_private",
    ),
    url(
        "^change$",
        auth_views.PasswordChangeView.as_view(
            form_class=forms.PasswordChangeForm,
            success_url=reverse_lazy("bid_main:password_change_done"),
        ),
        name="password_change",
    ),
    url(
        "^change-password/done$",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    url(
        r"^password_reset/$",
        auth_views.PasswordResetView.as_view(
            form_class=forms.PasswordResetForm,
            success_url=reverse_lazy("bid_main:password_reset_done"),
        ),
        name="password_reset",
    ),
    url(
        r"^password_reset/done/$",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    url(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("bid_main:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    url(
        r"^password_reset/complete/$",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("ev-members", json_api.EvMembersView.as_view(), name="ev-members"),
    path(
        "user/<slug:nickname>/",
        normal_pages.PublicProfileView.as_view(),
        name="public-profile",
    ),
    url(
        r"^confirm-email/start$",
        registration_email.ConfirmEmailView.as_view(),
        name="confirm-email",
    ),
    url(
        r"^confirm-email/start-change$",
        registration_email.ConfirmEmailView.as_view(
            template_name="bid_main/confirm_email/change.html"
        ),
        name="confirm-email-change",
    ),
    url(
        r"^confirm-email/cancel-change$",
        registration_email.CancelEmailChangeView.as_view(),
        name="cancel-email-change",
    ),
    url(
        r"^confirm-email/sent$",
        registration_email.ConfirmEmailSentView.as_view(),
        name="confirm-email-sent",
    ),
    url(
        r"^confirm-email/verified/(?P<info>[^/]+)/(?P<hmac>[^/]+)$",
        registration_email.ConfirmEmailVerifiedView.as_view(),
        name="confirm-email-verified",
    ),
    url(
        r"^confirm-email/poll$",
        registration_email.ConfirmEmailPollView.as_view(),
        name="confirm-email-poll",
    ),
]

if not settings.DISABLE_ACOUNT_CREATION:
    urlpatterns += [
        # Source of registration machinery:
        # http://musings.tinbrain.net/blog/2014/sep/21/registration-django-easy-way/
        url(
            r"^register/$",
            registration_email.RegistrationView.as_view(),
            name="register",
        ),
        url(
            r"^register/signed-up/$",
            auth_views.PasswordResetDoneView.as_view(
                template_name="registration/initial_signed_up.html"
            ),
            name="register-done",
        ),
        url(
            r"^register/password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
            registration_email.InitialSetPasswordView.as_view(),
            name="register-confirm",
        ),
        url(
            r"^register/complete/$",
            auth_views.PasswordResetCompleteView.as_view(
                template_name="registration/registration_complete.html"
            ),
            name="register-complete",
        ),
    ]

if settings.ENABLE_DEV_REQUESTS:
    urlpatterns += [
        path(
            "developer-access-pending",
            developer_request.DeveloperRequestPending.as_view(),
            name="developer-access-pending",
        ),
        path(
            "developer-access-request",
            developer_request.DeveloperRequestView.as_view(),
            name="developer-access-request",
        ),
        path(
            "developer-access-cancel",
            developer_request.DeveloperRequestCancelView.as_view(),
            name="developer-access-cancel",
        ),
        path(
            "developer-access-request/verification/<int:pk>",
            developer_request.DeveloperRequestVerificationView.as_view(),
            name="developer-access-request-verification",
        ),
    ]

# Only enable this on a dev server:
if settings.DEBUG:
    from .views import testviews

    urlpatterns += [
        url(r"^debug/email-changed$", testviews.test_mail_email_changed),
        url(r"^debug/email-verify$", testviews.test_mail_verify_address),
        url(r"^error/(?P<code>\d+)$", testviews.test_error),
    ]

templates/_footer.html
<footer id="kFooter" class="footer">
    <section id="kLinks" class="container">
      <div class="row">
        <nav class="col-sm">
          <h3>Products</h3>
          <a href="https://kde.org/plasma-desktop">Plasma</a>
          <a href="https://kde.org/applications/">KDE Applications</a>
          <a href="https://kde.org/products/frameworks/">KDE Frameworks</a>
          <a href="https://plasma-mobile.org/overview/">Plasma Mobile</a>
          <a href="https://neon.kde.org/">KDE neon</a>
          <a href="https://wikitolearn.org/" target="_blank">WikiToLearn</a>
        </nav>

        <nav class="col-sm">
          <h3>Develop</h3>
          <a href="https://techbase.kde.org/">TechBase Wiki</a>
          <a href="https://api.kde.org/">API Documentation</a>
          <a href="https://doc.qt.io/" target="_blank">Qt Documentation</a>
          <a href="https://inqlude.org/" target="_blank">Inqlude Documentation</a>
          <a href="https://kde.org/goals">Goals</a>
        </nav>

        <nav class="col-sm">
          <h3>News &amp; Press</h3>
          <a href="https://kde.org/announcements/">Announcements</a>
          <a href="https://dot.kde.org/">KDE.news</a>
          <a href="https://planetkde.org/">Planet KDE</a>
          <a href="https://www.kde.org/screenshots">Screenshots</a>
          <a href="https://www.kde.org/contact/">Press Contact</a>
        </nav>

        <nav class="col-sm">
          <h3>Resources</h3>
          <a href="https://community.kde.org/Main_Page">Community Wiki</a>
          <a href="https://userbase.kde.org/">UserBase Wiki</a>
          <a href="https://kde.org/stuff/">Miscellaneous Stuff</a>
          <a href="https://kde.org/support/">Support</a>
          <a href="https://kde.org/support/international.php">International Websites</a>
          <a href="https://kde.org/download/">Download KDE Software</a>
          <a href="https://kde.org/code-of-conduct/">Code of Conduct</a>
          <a href="https://kde.org/privacypolicy">Privacy Policy</a>
          <a href="https://kde.org/privacypolicy-apps">Applications Privacy Policy</a>
        </nav>

        <nav class="col-sm">
          <h3>Destinations</h3>
          <a href="https://store.kde.org/">KDE Store</a>
          <a href="https://ev.kde.org/">KDE e.V.</a>
          <a href="https://www.kde.org/community/whatiskde/kdefreeqtfoundation.php">KDE Free Qt Foundation</a>
          <a href="https://timeline.kde.org/">KDE Timeline</a>
        </nav>
      </div>
    </section>

    <section id="kSocial" class="container kSocialLinks">
      <a class="shareFacebook" href="https://www.facebook.com/kde/" rel="nofollow">Post on Facebook</a>
      <a class="shareTwitter" href="https://twitter.com/kdecommunity" rel="nofollow">Share on Twitter</a>
      <a class="shareDiaspora" href="https://joindiaspora.com/people/9c3d1a454919ef06" rel="nofollow">Share on Diaspora</a>
      <a class="shareMastodon" href="https://mastodon.technology/@kde" rel="me nofollow">Share on Mastodon</a>
      <a class="shareLinkedIn" href="https://www.linkedin.com/company/29561/" rel="nofollow">Share on LinkedIn</a>
      <a class="shareReddit" href="https://www.reddit.com/r/kde/" rel="nofollow">Share on Reddit</a>
      <a class="shareYouTube" href="https://www.youtube.com/channel/UCF3I1gf7GcbmAb0mR6vxkZQ" rel="nofollow">Share on YouTube</a>
      <a class="sharePeerTube" href="https://peertube.mastodon.host/accounts/kde/videos" rel="nofollow">Share on PeerTube</a>
      <a class="shareVK" href="https://vk.com/kde_ru" rel="nofollow">Share on VK</a>
    </section>

    <section id="kLegal" class="container">
      <div class="row">
        <small class="col-4">
          Maintained by <a href="mailto:sysadmin@kde.org">KDE Sysadmins</a>
        </small>
        <small class="col-8 text-right">
          KDE<sup>®</sup> and <a href="/media/images/trademark_kde_gear_black_logo.png">the K Desktop Environment<sup>®</sup> logo</a> are registered trademarks of <a href="https://ev.kde.org/" title="Homepage of the KDE non-profit Organization">KDE e.V.</a> |
          <a href="https://www.kde.org/community/whatiskde/impressum">Legal</a>
        </small>
      </div>
    </section>
</footer>

templates/_navbar.html
<header id="KGlobalHeader" class="header clearfix">
  <nav class="navbar navbar-expand">
    <a aria-label="KDE Homepage" class="kde-logo navbar-brand active" href="/">KDE Accounts</a>
    {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ settings.LOGOUT_URL }}">Log out</a>
          </li>
        </ul>
      </div>
    {% endif %}
  </nav>
</header>

templates/email_layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{{ subject }}{% endblock %}</title>
    <style>
      html, body {
      	background-color: white;
      	color: black;
      	font-family: 'Roboto', 'Noto Sans', sans-serif;
      	font-size: 10pt;
      }
      
      body {
      	max-width: 100%;
      	width: 60ex;
      	margin-right: auto;
      	padding: 0.5em 1em;
      }
      
      p {
      	line-height: 150%;
      }
      p.closing {
      	margin-top: 3.5em;
      }
      
      section.about {
      	margin-top: 2em;
      	color: #888;
      }
    </style>
  </head>
  <body>
    {% block body %}{% endblock %}
    <p class="closing">Kind regards,</p>
    <p>The KDE Sysadmin team</p>
  </body>
</html>

templates/layout.html
{% comment %}
SPDX-FileCopyright: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: GPl-3.0-or-later
{% endcomment %}
{% load static %}
{% load flatpages %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block page_title %}Home{% endblock %} - KDE Accounts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="KDE Accounts is a unified login system for all services around KDE.">
    <meta name="author" content="Blender Foundation, KDE">
    <link type="text/x-scss" href="/static/assets/css/base.css" rel="stylesheet">
    <link href="https://cdn.kde.org/aether-devel/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.kde.org/aether-devel/aether-kde-org.css" rel="stylesheet">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    {% block modal %}
    {% endblock %}

    {% block navigation_header %}
      {% include "_navbar.html" %}
    {% endblock navigation_header %}

    {% block header %} {% endblock %}
    <main>
      <div class="container">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            <div class="container">
              {{ message }}
              <button class="close" type="button" data-dismiss="alert">Close</button>
            </div>
          </div>
        {% endfor %}

        {% if user and user.must_pp_agree %}
          {% block privacy_policy_banner %}
          <article class="privacy-policy-must-agree alert alert-warning">
            <h1>Our Privacy Policy Changed</h1>
            <p>
              In order to continue using KDE Accounts, please accept <a href="{% url 'bid_main:privacy_policy_agree' %}">
              our new privacy policy</a>.
            </p>
          </article>
          {% endblock %}
        {% endif %}
      </div>
      <div class="container">
        {% block body %}{% endblock %}
      </div>
      {% block bodyfluid %}{% endblock %}
    </main>
    <script src="https://cdn.kde.org/aether-devel/bootstrap.js"></script>
    {% block footer_scripts %}{% endblock footer_scripts %}

    {% block footer %}
      {% include "_footer.html" %}
    {% endblock footer %}
    {% block js %}
    {% endblock %}
  </body>
</html>

templates/profile_layout.html
{% extends 'layout.html' %}
{% comment %}
SPDX-FileCopyright: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: GPl-3.0-or-later
{% endcomment %}

{% block bodyfluid %}
<div class="container-fluid">
  <div class="row border-bottom">
    <div class="col-md-3 px-0">
<style>
.aether-list-item {
  padding-left: 15px;
  padding-right: 15px;
  border-left: 4px solid transparent;
  min-height: 2.5rem;
  line-height: 2.5rem;
  vertical-align: middle;
}
.aether-list-item:hover {
  border-left-color: #54a3d8;
  background: rgba(84,163,216,.12549019607843137);
}
.aether-list-item.active {
  border-left-color: #54a3d8;
  background: rgba(84,163,216,.17549019607843137);
}

</style>
      <div class="d-flex flex-column border-right h-100">
        <a class="aether-list-item {% if request.path == "/" %} active{% endif %}" href="{% url 'bid_main:index' %}">Overview</a>
        <a class="aether-list-item {% if request.path == "/change" %} active{% endif %}" href="{% url 'bid_main:password_change' %}">Change Password</a>
        <a class="aether-list-item {% if request.path == "/settings/profile" %} active{% endif %}" href="{% url 'bid_main:profile' %}">Edit profile</a>
        {% if settings.ENABLE_DEV_REQUESTS and 'developers' not in user.role_names %}
        <a class="aether-list-item" href="{% url 'bid_main:developer-access-request' %}">Request developer
          access</a>
        {% endif %}
        <a class="aether-list-item {%if request.path == "/account/two_factor/" %} active{% endif %}" href="{% url 'two_factor:profile' %}">
          Two-Factor Authentication Configuration
        </a>
        <a class="aether-list-item" href="{% url 'bid_main:delete_user' %}">Delete account</a>
      </div>
    </div>
    <div class="col px-0">
     {% block setting %}
     {% endblock %}
    </div>
  </div>
</div>
{% endblock %}